#!/bin/bash

echo -e "\e[33m iam printing in yellow colour \e[0m"
echo -e "\e[32m iam printing in yellow colour \e[0m"
echo -e "\e[34m iam printing in yellow colour \e[0m"
echo -e "\e[44;32m iam printing in yellow colour \e[0m"
