#!/bin/bash

a="abc"

if [ "$a" == "abc" ] ; then
   echo -e "\e[32m both of them are equal \e[0m"
   exit 0
else
   echo -e "\e[31m both them are not equal \e[0m"
   exit 1   

fi

# sjvdjbkasbccjh

c=$1

if [ "$c" -eq "10" ] ; then
   echo "value of c is 10"
elif [ "$c" -eq "20" ] ; then
   echo "value of c is 20"
elif [ "$c" -eq "30" ] ; then
   echo "value of c is 30"
else "value is not 10 or 20 or 30"

fi        
