- name: Demo on facts
  hosts: all
  tasks:
    - name: print OS Distro
      debug:
        msg: OS Distro is {{ ansible_distribution }}
    - name: print Mac Address
      debug:     # debug: or ansible.builtin.debug:  both will work
        msg: Mac Address {{ ansible_default_ipv4.macaddress }}