- name: Ansible task selection
  hosts: all
  tasks:
    - name: Performing webserver installation
      ansible.builtin.debug:
          msg: webserver installation completed
      tags: web    
    - name: starting webserver
      ansible.builtin.debug:
          msg: webserver started
      tags: web    

    - name: Performing appserver installation
      ansible.builtin.debug:
          msg: appserver installation completed
      tags: app
    - name: starting appserver
      ansible.builtin.debug:
          msg: appserver started
      tags: app    

    - name: Performing dbserver installation
      ansible.builtin.debug:
          msg: dbserver installation completed
      tags: db
    - name: starting dbserver
      ansible.builtin.debug:
          msg: dbserver started
      tags: db            

      #if your palybook there are having "n" number of tasks. if you want to run specific thing related task
      # answer::  using tags {ex: -t app or -t web or -t db}