- name: demo on privilage escalition
  hosts: all
  become: yes
  tasks:
    - name: Running a shell commands
      ansible.builtin.shell: id
      register: OUT

    - name: Printing the out variable
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}" 