- name: Play1
  hosts: prod
  tasks:
    - name: Print Hello from task1 of Pay1
      ansible.builtin.debug:
         msg: hai from task1 of Pay1

    - name: Print Hello from task2 of Pay1
      ansible.builtin.debug:
          msg: hai from task2 of Pay1
