- name: adding application user
  ansible.builtin.user:
    name: roboshop
    comment: roboshop application user
  register: APP_USER_INFO

- name: print the app user info
  debug:
    msg: "{{APP_USER_INFO}}"