- name: installing maven
  ansible.builtin.yum:
    name: maven
    state: present

- name: Creating roboshop user account 
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: downloading and extracting component
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: cleanig the old content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: copy file
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/  
    remote_src: yes
  become_user: roboshop

- name: creating a package
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir:  /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: configuring the service
  ansible.builtin.include_role:
    name: common
    tasks_from: config-service

- name: Doing set-hostname 
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname 
