- name: Copying Redis repo 
  ansible.builtin.copy:
     src: redis.repo 
     dest: /etc/yum.repos.d/redis.repo 

- name: Install Redis 
  ansible.builtin.package:
    name: redis
    state: present

- name: Update Redis Config
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: yes 

- name: Restart Redis service
  become: true
  service:
    name: redis
    state: restarted

- name: Doing set-hostname 
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname

