- name: copying the repo
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: installing redis
  ansible.builtin.package:
    name: redis
    state: installed

- name: update redis config
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: start the redis service
  ansible.builtin.service:
    state: started
    name: redis
    enabled: yes

- name: doing set-hostname
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname
