- name: copy mysql repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: installing mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed


- name: starting mysql
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes


